# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5ef6acb0dd25d2838aaa8c52cdc47152"
application_url = "https://pull--dollars-barriers.trycloudflare.com"
embedded = true
name = "Test"
handle = "test-17914"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pull--dollars-barriers.trycloudflare.com/auth/callback",
  "https://pull--dollars-barriers.trycloudflare.com/auth/shopify/callback",
  "https://pull--dollars-barriers.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
